version: '3'

services:
  brewing_support:
    container_name: brewing_support
    build: 
      dockerfile: "Dockerfile"
      context: "execution_environment"
    volumes:
      - type: bind
        source: ../build
        target: /workspace
    expose:
      - 8080
    tty: true
    depends_on: 
      - brewing_support_postgres_db
      - brewing_support_couch_db
  brewing_support_postgres_db:
    image: postgres:11.3
    container_name: brewing_support_postgres_db
    environment: 
      POSTGRES_USER: "brewing_support"
      POSTGRES_PASSWORD: "brewing_support"
      POSTGRES_DB: "brewing_supportdb"
  brewing_support_couch_db:
    image: couchdb:3.2
    container_name: brewing_support_couch_db
    volumes:
      - ./execution_environment/couchdb/data:/opt/couchdb/data
      - ./execution_environment/couchdb/config:/opt/couchdb/etc/local.d
    expose:
      - 5984
    environment: 
      COUCHDB_USER: "brewing_support"
      COUCHDB_PASSWORD: "brewing_support"
  reverse-proxy:
    container_name: reverse-proxy
    image: nginx
    volumes:
      - ./execution_environment/reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./execution_environment/reverse-proxy/log:/var/log/nginx
      - ./execution_environment/reverse-proxy/doc:/var/www/html
      - ./execution_environment/certs:/etc/nginx/conf.d/ssl
      - ./execution_environment/letsencrypt:/etc/nginx/conf.d/letsencrypt
    ports:
      - "80:80"
      - "443:443"
      - "5984:5984"
    depends_on:
      - brewing_support
  certbot:
    image: certbot/certbot:v1.7.0
    container_name: certbot
    volumes:
      - ./execution_environment/letsencrypt:/etc/letsencrypt
      - ./execution_environment/reverse-proxy/doc:/var/www/html
    command: ["--version"]
